REFACTOR0070: Add RSPEC routing and requests to CI pipeline

diff --git a/.lighthouse/jenkins-x/pullrequest/unit-test.yaml b/.lighthouse/jenkins-x/pullrequest/unit-test.yaml
--- a/.lighthouse/jenkins-x/pullrequest/unit-test.yaml
+++ b/.lighthouse/jenkins-x/pullrequest/unit-test.yaml
@@ -33,7 +33,7 @@ spec:
           name: check-registry
           resources: {}
         - image: ruby:3.0.3
-          name: unit-test-models-test 
+          name: models-test 
           resources: {}
           script: |
             #!/bin/bash
@@ -42,16 +42,16 @@ spec:
             echo "-------- RSPEC | START --------"
             bundle exec rspec spec/models
             echo "-------- RSPEC | END --------"
-        # - image: ruby:3.0.3
-        #   name: unit-test-controller-test
-        #   resources: {}
-        #   script: |
-        #     #!/bin/bash
-        #     set -e # Makes terminal exit on error
-        #     bundle install 
-        #     echo "-------- RSPEC | START --------"
-        #     bundle exec rspec spec/requests
-        #     echo "-------- RSPEC | END --------"
+        - image: ruby:3.0.3
+          name: controller-test
+          resources: {}
+          script: |
+            #!/bin/bash
+            set -e # Makes terminal exit on error
+            bundle install 
+            echo "-------- RSPEC | START --------"
+            bundle exec rspec spec/requests
+            echo "-------- RSPEC | END --------"
   podTemplate: {}
   serviceAccountName: tekton-bot
   timeout: 12h0m0s
