Revert "REFACTOR0008: Temp remove ruby lint and security PR build steps"
This reverts commit eeadb695d892b793dfbcc0a848172e51f9f0661b.

diff --git a/.lighthouse/jenkins-x/pullrequest.yaml b/.lighthouse/jenkins-x/pullrequest.yaml
--- a/.lighthouse/jenkins-x/pullrequest.yaml
+++ b/.lighthouse/jenkins-x/pullrequest.yaml
@@ -32,53 +32,53 @@ spec:
         - image: ghcr.io/jenkins-x/jx-registry:0.1.1
           name: check-registry
           resources: {}
-        # - image: ruby:3.0.3
-        #   name: ruby-lint #lint ruby script
-        #   resources: {}
-        #   script: |
-        #     #!/bin/bash
+        - image: ruby:3.0.3
+          name: ruby-lint #lint ruby script
+          resources: {}
+          script: |
+            #!/bin/bash
 
-        #     set -e # Makes terminal exit on error
-        #     apt update
-        #     apt install nodejs -y
-        #     node -v
-        #     apt install npm -y
+            set -e # Makes terminal exit on error
+            apt update
+            apt install nodejs -y
+            node -v
+            apt install npm -y
 
-        #     # For Prettier - ESLint - stylelint
-        #     npm install --save-dev prettier-eslint
-        #     npm install --save-dev prettier-eslint-cli
-        #     npm install prettier-stylelint --save-dev
+            # For Prettier - ESLint - stylelint
+            npm install --save-dev prettier-eslint
+            npm install --save-dev prettier-eslint-cli
+            npm install prettier-stylelint --save-dev
 
-        #     # Standrd Ruby on Rails bundle install
-        #     bundle install
+            # Standrd Ruby on Rails bundle install
+            bundle install
 
-        #     echo "-------- RUBOCOP | START --------"
-        #     cd ./bin
-        #     chmod u+r+x error_handler.sh
-        #     ./error_handler.sh "rubocop --parallel"; cd ..
-        #     echo "-------- RUBOCOP | END --------"
+            echo "-------- RUBOCOP | START --------"
+            cd ./bin
+            chmod u+r+x error_handler.sh
+            ./error_handler.sh "rubocop --parallel"; cd ..
+            echo "-------- RUBOCOP | END --------"
             
-        #     echo "-------- Prettier - ESLint - stylelint | START --------"
-        #     cd ./bin 
-        #     ./error_handler.sh "npm run fix-code"
-        #     ./error_handler.sh "npm run fix-styles"
-        #     cd ..
-        #     echo "-------- Prettier - ESLint - stylelint | END --------"
-        # - image: ruby:3.0.3
-        #   name: ruby-security-checks # Brakeman security test
-        #   resources: {}
-        #   script: |
-        #     #!/bin/bash
-        #     gem install brakeman
-        #     brakeman -aq
-        # - image: gcr.io/kaniko-project/executor:v1.6.0-debug
-        #   name: build-container-build
-        #   resources: {}
-        #   script: |
-        #     #!/busybox/sh
-        #     source .jx/variables.sh
-        #     cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
-        #     /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=${DOCKERFILE_PATH:-Dockerfile} --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
+            echo "-------- Prettier - ESLint - stylelint | START --------"
+            cd ./bin 
+            ./error_handler.sh "npm run fix-code"
+            ./error_handler.sh "npm run fix-styles"
+            cd ..
+            echo "-------- Prettier - ESLint - stylelint | END --------"
+        - image: ruby:3.0.3
+          name: ruby-security-checks # Brakeman security test
+          resources: {}
+          script: |
+            #!/bin/bash
+            gem install brakeman
+            brakeman -aq
+        - image: gcr.io/kaniko-project/executor:v1.6.0-debug
+          name: build-container-build
+          resources: {}
+          script: |
+            #!/busybox/sh
+            source .jx/variables.sh
+            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
+            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=${DOCKERFILE_PATH:-Dockerfile} --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
         - image: ghcr.io/jenkins-x-plugins/jx-preview:0.0.192
           name: promote-jx-preview
           resources: {}
