REFACTOR0015: Add db migrate to release yaml

diff --git a/.lighthouse/jenkins-x/release.yaml b/.lighthouse/jenkins-x/release.yaml
--- a/.lighthouse/jenkins-x/release.yaml
+++ b/.lighthouse/jenkins-x/release.yaml
@@ -48,14 +48,32 @@ spec:
         - image: ghcr.io/jenkins-x/jx-registry:0.1.1
           name: check-registry
           resources: {}
+          - image: ruby:3.0.3
+          name: ruby-db-migrations 
+          resources: {}
+          script: |
+            #!/bin/bash
+
+            set -e # Makes terminal exit on error
+            apt update
+            apt-get install -y postgresql
+            # Standrd Ruby on Rails bundle install
+            bundle install
+
+            echo "-------- Migrate Staging | START --------"
+            RAILS_ENV=development rake db:migrate
+            echo "-------- Migrate Staging | END --------"
+            
+            echo "-------- Migrate Production | START --------"
+            RAILS_ENV=production rake db:migrate
+            echo "-------- Migrate Production | END --------"
         - image: gcr.io/kaniko-project/executor:v1.6.0-debug
           name: build-container-build
           resources: {}
           script: |
             #!/busybox/sh
-            source .jx/variables.sh
-            #sed -i 's/ENV RAILS_ENV development/ENV RAILS_ENV production/g' $DOCKERFILE_PATH
             cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
+            sed -i 's/ENV RAILS_ENV development/ENV RAILS_ENV production/g' $DOCKERFILE_PATH
             /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=${DOCKERFILE_PATH:-Dockerfile} --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
         - image: ghcr.io/jenkins-x/jx-changelog:0.1.3
           name: promote-changelog
