TEMP0001: Modify release.yaml

diff --git a/.lighthouse/jenkins-x/release.yaml b/.lighthouse/jenkins-x/release.yaml
--- a/.lighthouse/jenkins-x/release.yaml
+++ b/.lighthouse/jenkins-x/release.yaml
@@ -48,28 +48,28 @@ spec:
         - image: ghcr.io/jenkins-x/jx-registry:0.1.1
           name: check-registry
           resources: {}
-        # - image: ruby:3.0.3
-        #   name: ruby-db-migrations 
-        #   resources: {}
-        #   script: |
-        #     #!/bin/bash
-        #     source .jx/variables.sh
-        #     set -e # Makes terminal exit on error
-        #     apt update
-        #     apt-get install -y postgresql
-        #     # Standrd Ruby on Rails bundle install
-        #     bundle install
-        #     unset VERSION
+        - image: ruby:3.0.3
+          name: ruby-db-migrations 
+          resources: {}
+          script: |
+            #!/bin/bash
+            source .jx/variables.sh
+            set -e # Makes terminal exit on error
+            apt update
+            apt-get install -y postgresql
+            # Standrd Ruby on Rails bundle install
+            bundle install
+            unset VERSION
 
-        #     echo "-------- Migrate Staging DB | START --------"
-        #     RACK_ENV=RAILS_ENV=development RAILS_ENV=development rake db:migrate
-        #     echo "-------- Migrate Staging DB | END --------"
+            echo "-------- Migrate Staging DB | START --------"
+            RACK_ENV=RAILS_ENV=development RAILS_ENV=development rake db:migrate
+            echo "-------- Migrate Staging DB | END --------"
              
-        #     echo "-------- Migrate Production DB | START --------"
-        #     RAKE_SECRET=$(RAILS_ENV=production rake secret)
-        #     export SECRET_KEY_BASE=$RAKE_SECRET
-        #     RACK_ENV=production RAILS_ENV=production bundle exec rake db:migrate
-        #     echo "-------- Migrate Production DB  | END --------"
+            echo "-------- Migrate Production DB | START --------"
+            RAKE_SECRET=$(RAILS_ENV=production rake secret)
+            export SECRET_KEY_BASE=$RAKE_SECRET
+            RACK_ENV=production RAILS_ENV=production bundle exec rake db:migrate
+            echo "-------- Migrate Production DB  | END --------"
         - image: gcr.io/kaniko-project/executor:v1.6.0-debug
           name: build-container-build
           resources: {}
@@ -77,7 +77,7 @@ spec:
             #!/busybox/sh
             source .jx/variables.sh
             cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
-            sed -i 's/ENV RAILS_ENV development/ENV RAILS_ENV production/g' $DOCKERFILE_PATH
+            #sed -i 's/ENV RAILS_ENV development/ENV RAILS_ENV production/g' $DOCKERFILE_PATH
             /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=${DOCKERFILE_PATH:-Dockerfile} --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
         - image: ghcr.io/jenkins-x/jx-changelog:0.1.3
           name: promote-changelog
