REFACTOR0084: Modify git_merge_and_push.sh

diff --git a/.lighthouse/jenkins-x/release.yaml b/.lighthouse/jenkins-x/release.yaml
--- a/.lighthouse/jenkins-x/release.yaml
+++ b/.lighthouse/jenkins-x/release.yaml
@@ -75,6 +75,25 @@ spec:
             echo "-------- Migrate Production DB  | END --------"
             chmod u+r+x ./bin/git_merge_and_push.sh
             ./bin/git_merge_and_push.sh BUILD_$SET_VERSION "DB-Migration: Re-generate schema" main "db/schema.rb"
+        - image: ruby:3.0.3
+          name: unit-test 
+          resources: {}
+          script: |
+            #!/bin/bash
+            source .jx/variables.sh
+            set -e # Makes terminal exit on error
+            bundle install 
+            echo "-------- RSPEC | START --------"
+            bundle exec rspec spec/models spec/features # spec/requests
+            echo "-------- RSPEC | END --------"
+            chmod u+r+x ./bin/commit_and_push.sh
+            ./bin/commit_and_push.sh BUILD_STATS "Unit-Test: Add $VERSION release coverage" main
+        - image: ghcr.io/jenkins-x/jx-boot:3.2.287
+          name: jx-variables-2
+          resources: {}
+          script: |
+            #!/usr/bin/env sh
+            jx gitops variables
         - image: gcr.io/kaniko-project/executor:v1.6.0-debug
           name: build-container-build
           resources: {}
@@ -115,19 +134,6 @@ spec:
             #!/usr/bin/env sh
             source .jx/variables.sh
             jx promote -b --all --timeout 1h --no-poll
-        - image: ruby:3.0.3
-          name: unit-test 
-          resources: {}
-          script: |
-            #!/bin/bash
-            source .jx/variables.sh
-            set -e # Makes terminal exit on error
-            bundle install 
-            echo "-------- RSPEC | START --------"
-            bundle exec rspec spec/models spec/features # spec/requests
-            echo "-------- RSPEC | END --------"
-            chmod u+r+x ./bin/commit_and_push.sh
-            ./bin/commit_and_push.sh BUILD_STATS "Unit-Test: Add $VERSION release coverage" main
   podTemplate: {}
   serviceAccountName: tekton-bot
   timeout: 12h0m0s
